### ISSUE TITLE
HS(V) colors

### ISSUE THREAD

**Issue by cherrydev** [Lamprichauns/lamp-os#11]
I think HSV (or really just hue + saturation) could be more useful than RGB for specifying the color of a lamp, because the 'V' (value/brightness) is going to vary according to a brightness setting and therefore the overall brightness of a color isn't really relevant, but only the hue and saturation. The RGB value of a pixel would then only be determined just before writing it out to the pixels. Since most people are much more familiar with RGB values, we could allow colors to originally be specified as RGB values, but then convert them to HSV for use internally.

**Comment by chaffneue** [comment]
This issue is super old now. We've moved to having a color picker in the web application which can quickly fine tune colors, so I'm going to close this issue
